wip

diff --git a/syncpass b/syncpass
--- a/syncpass
+++ b/syncpass
@@ -24,37 +24,19 @@ imp "./utils/import_settings"
 imp "./utils/import_ssh"
 
 
-versions_are_unsynced() {
-    # 0 = needs update
-    local server_ver=$(func_get_server_version)
-    if [[ $server_ver -eq $V ]]; then
-        return 1
+confirm() {
+    if [[ -n "$1" ]]; then
+        read -p "$1 (y/n): " -n 1 -r
+        echo    # Move to new line
+        [[ $REPLY =~ ^[Yy]$ ]]
     else
-        return 0
+        read -p "Are you sure? (y/n): " -n 1 -r
+        echo    # Move to new line
+        [[ $REPLY =~ ^[Yy]$ ]]
     fi
 }
 
 case "$1" in
-    add|edit)
-        # pull server version to see if update is needed
-        # push version update to server
-        echo -e "found add/edit\n"
-        pass $@ 2>&1
-        exit_code=$?
-
-        if [ $exit_code -eq 0 ]; then
-            echo -e "add/edit success\n"
-            func_increment_version
-            func_update_server_passwordstore
-
-            curr_ver=$(func_get_local_version)
-            func_update_server_version $curr_ver
-        else
-            echo -e "add/edit failed\n"
-        fi
-        ;;
-    test)
-        ;;
     init)
         func_init_local
         server_home_path=$(func_get_server_home_path)
@@ -65,21 +47,126 @@ case "$1" in
         # back it up in current directory
         ;;
     *)
+        ;;
+esac
+
+# settings check, return 1 if no settings avail
+
+case "$1" in
+    add|edit|generate|rm)
+        # push new version to server after command is finished running
+        if pass $@; then
+            func_increment_version
+            echo -e "✓ Local version updated"
+
+            # update server's passwordstore
+            func_update_server_passwordstore
+
+            # update server's version
+            curr_ver=$(func_get_local_version)
+            func_update_server_version $curr_ver
+            echo -e "✓ Server version updated"
+        else
+            echo -e "✗ pass command failed."
+        fi
+        ;;
+    inject)
+        func_update_server_passwordstore
+        ;;
+    help)
+        func_print_settings
+        ;;
+    *)
+        args=("$@")
+        first_non_flag=""
+        
+        for arg in "${args[@]}"; do
+            if [[ "$arg" != -* ]]; then
+                first_non_flag="$arg"
+                break
+            fi
+        done
+
+        case "$first_non_flag" in
+            ls|find|grep|insert|edit|generate|rm|mv|cp|git) return 1 ;;
+            "") 
+                echo -e "✗ Syncpass could not determine the pass command."
+                exit 1
+                ;;
+            *)
+                ## Probably trying to get password
+                ### Sync server and local before running pass
+
+                server_ver=$(func_get_server_version)
+
+                echo "✓ SSH successful"
+
+                if (( server_ver == VERSION )); then
+                    echo -e "✓ Syncpass versions on server and local are synced."
+                elif (( server_ver < VERSION ));then
+                    echo -e ">>> WARNING: Local version is ahead of server"
+                    echo -e ">>> Recommending to run 'syncpass sync'"
+                else
+                    echo -e "✗ Local .password-store is behind server, preparing to update"
+                    if confirm "> Are you sure you want to overwrite/update your local .password-store with the one from the server?"; then
+                        echo -e ">>> Preparing to update your local password-store ..."
+                    else
+                        echo -e "> Exiting syncpass, no changes have been made."
+                        exit 1
+                    fi
+
+                    # backup local .password-store
+                    sp_filename="${C_PATH}/.password-store_backup.tar.gz"
+                    if cd $HOME && tar -czf $sp_filename .password-store; then
+                        echo -e "✓ Backed up local ~/.password-store to .password-store_backup.tar.gz"
+                    else
+                        echo -e "✗ tar command for backing up failed."
+                        exit 1
+                    fi
+
+                    # pull password-store from server
+                    func_get_server_passwordstore
+
+                    # unzip it to local
+                fi
+
+                pass $@ 2>&1
+                exit_code=$?
+
+                if [ $exit_code -ne 0 ]; then
+                    echo -e "✗ pass command failed."
+                fi
+                exit 0
+                ;;
+        esac
+
         if [[ -n "$1" ]]; then
             folder=$1
 
-            local needs_update=$(versions_are_unsynced)
-            if [[ $needs_update -eq 0 ]]; then
+            server_ver=$(func_get_server_version)
+
+            if (( server_ver == VERSION )); then
+                echo -e ">>> Syncpass versions on server and local are synced. \n"
+            elif (( server_ver < VERSION ));then
+                echo -e ">>> Local version is ahead of server \n"
                 echo -e ">>> Syncpass versions on server and local are unsynced, updating ...\n"
             else
-                echo -e ">>> Syncpass Versions on server and local are synced. \n"
+                echo -e ">>> Local version is behind server, preparing to update ...\n"
+                # backup local to a _backup_timestamp.tar.gz
+                sp_filename="${C_PATH}/.password-store_backup.tar.gz"
+                compressed_zip=$(cd $HOME && tar -czf $sp_filename .password-store)
+                echo -e ">>> Backed up local ~/.password-store to .password-store_backup.tar.gz"
             fi
-            local password=$(pass show $folder)
-            # pull version to update if there is change if result is success
-            echo $password
-            exit 0
+
+            if password=$(pass show "$folder" 2>/dev/null); then
+                echo $password
+            else
+                echo -e "> Failed to retrieve password for '$folder'"
+                exit 1
+            fi
+
+        elif [ $# -eq 0 ]; then
+            pass
         fi
-        func_print_settings
-        echo "Show help commands"
         ;;
 esac
diff --git a/utils/import_ssh b/utils/import_ssh
--- a/utils/import_ssh
+++ b/utils/import_ssh
@@ -28,64 +28,102 @@ func_server_setup_syncpass_version() {
     echo $result
 }
 
+# impo
 func_get_server_version() {
-    local version=$($SSH_COMMAND "cat $SYNCPASS_VERSION_PATH" | grep "VERSION=" | cut -d'=' -f2)
-    echo $version
-}
-
-func_update_server_version() {
-    local new_version=$1
-
-    $($SSH_COMMAND "echo \"VERSION=$new_version\" > $SYNCPASS_VERSION_PATH")
-}
-
-func_update_server_passwordstore() {
-    # requirement: C_PATH
-    if [ -d ~/.password-store ]; then
-        printf ">>> Found .password-store, preparing to send to server.\n"
-        # TODO verify env settings
-        printf ">>> Compressing local .password-store ...\n"
-        local compressed_zip_path="${C_PATH}/$PASSWORD_STORE_ZIP_FILENAME_LOCAL"
-        local compressed_zip=$(cd $HOME && tar -czf $compressed_zip_path .password-store)
-        printf ">>> Compressed local .password-store to $compressed_zip_path\n"
-
-        printf ">>> Sending to server ...\n"
-        local scp_command=$(private_func_get_scp_command "~/$PASSWORD_STORE_ZIP_FILENAME_SERVER" "$compressed_zip_path")
-        local send_zip=$($scp_command)
-        stty sane
-        printf ">>> Sent local .password-store\n"
-
-        printf ">>> Updating server's password-store ...\n"
-        $($SSH_COMMAND "mkdir -p ~/.password-store && tar -xzf ~/$PASSWORD_STORE_ZIP_FILENAME_SERVER -C ~/")
-        printf ">>> Finished updating the server's password-store\n"
+    if $SSH_COMMAND "cat $SYNCPASS_VERSION_PATH" | grep "VERSION=" | cut -d'=' -f2; then
+        echo $version
     else
-        printf "> Could not find .password-store, try creating passwords locally first\n"
+        echo -e "✗ ERROR - func_get_server_version: SSH command failed."
+        exit 1
     fi
 }
 
+# impo
+func_update_server_version() {
+    if [[ -n "$1" ]]; then
+        if $SSH_COMMAND "echo \"VERSION=$1\" > $SYNCPASS_VERSION_PATH"; then
+            echo "✓ SSH successful"
+        else
+            echo -e "✗ ERROR - func_update_server_version: SSH command failed."
+            exit 1
+        fi
+    else
+        echo -e "✗ ERROR - func_update_server_version: Version arguement required."
+        exit 1
+    fi
+}
+
+# impo
+func_update_server_passwordstore() {
+    # requirement: C_PATH
+    # TODO verify env settings
+    if [ -d ~/.password-store ]; then
+        echo -e ">>> Found .password-store, preparing to send to server."
+    else
+        echo -e "> Could not find .password-store, try creating passwords locally first"
+        exit 1
+    fi
+
+    # compress local .password-store
+    echo -e ">>> Compressing local .password-store ..."
+    local compressed_zip_path="${C_PATH}/$PASSWORD_STORE_ZIP_FILENAME_LOCAL"
+    if cd $HOME && tar -czf $compressed_zip_path .password-store; then
+        echo -e "✓ Compressed local .password-store to $compressed_zip_path\n"
+    else
+        echo -e "✗ ERROR - func_update_server_passwordstore: Compressing local .password-store failed."
+        exit 1
+    fi
+
+    # send compressed local to server
+    if $(private_func_get_scp_command "~/${PASSWORD_STORE_ZIP_FILENAME_SERVER}" $compressed_zip_path); then
+        echo -e "\n✓ Sent local .password-store to the server"
+    else
+        echo -e "✗ ERROR - func_update_server_passwordstore: SCP command failed."
+        exit 1
+    fi
+
+    stty sane
+
+    # # decompress sent local on the server
+    # if $SSH_COMMAND "mkdir -p ~/.password-store && tar -xzf ~/$PASSWORD_STORE_ZIP_FILENAME_SERVER -C ~/"; then
+    #     echo -e "✓ Successfully synced local .password-store to the server"
+    # else
+    #     echo -e "✗ ERROR - func_update_server_passwordstore: SCP command failed."
+    #     exit 1
+    # fi
+}
+
+#impo
 func_get_server_passwordstore() {
     # requirement: settings: C_PATH
     # TODO check if settings exist
 
-    # 0 = has password store
-    local password_store_exists=$($SSH_COMMAND "
-        if [ -d ~/.password-store ]; then
-            return 0
-        else
-            return 1
-        fi
-    ")
-
-    if [[ $password_store_exists -eq 1 ]]; then
-        echo "> .password-store does not exist on the server, try uploading passwords first"
+    if $SSH_COMMAND "[ -f ~/$PASSWORD_STORE_ZIP_FILENAME_SERVER ]"; then
+        echo -e "✓ Found .password-store copy on server\n"
+        # if $SSH_COMMAND "tar -czf ~/$PASSWORD_STORE_ZIP_FILENAME_SERVER ~/.password-store"; then
+        #     echo -e "✓ Compressed .password-store on server\n"
+        # else
+        #     echo -e "✗ ERROR - func_get_server_passwordstore: SSH command failed."
+        #     exit 1
+        # fi
+    else
+        echo "✗ .password-store does not exist on the server, try uploading passwords first"
         exit 1
     fi
 
-    # this will overwrite the current version
-    local zip_pass=$($SSH_COMMAND "tar -czf ~/$PASSWORD_STORE_ZIP_FILENAME_SERVER ~/.password-store")
-    # TODO confirm success
-    
-    local download_pass_command=$(private_func_get_scp_command "~/${PASSWORD_STORE_ZIP_FILENAME_SERVER}")
-    local download_pass=$($download_pass_command $C_PATH)
-    # TODO confirm success
+    # download server's password store on local
+    if $(private_func_get_scp_command "~/${PASSWORD_STORE_ZIP_FILENAME_SERVER}") $C_PATH; then
+        echo -e "\n✓ Downloaded .password-store from server -> $PASSWORD_STORE_ZIP_FILENAME_SERVER"
+    else
+        echo -e "✗ ERROR - func_get_server_passwordstore: SCP command failed."
+        exit 1
+    fi
+
+    # # unzip downloaded
+    if tar -xzf "$C_PATH/$PASSWORD_STORE_ZIP_FILENAME_SERVER"  -C ~/; then
+        echo -e "✓ Successfully synced local .password-store from the server"
+    else
+        echo -e "✗ ERROR - func_get_server_passwordstore: tar command failed."
+        exit 1
+    fi
 }
